### ISSUE TITLE
he system cannot find the path specified

### ISSUE THREAD

**Issue by raliqala** [lewislbr/ready#4]
Hello

I'm getting this error when i try to commit.  

am using
- [ ] windows 10
- [ ] go version go1.17.3 windows/amd64

Error
```
git commit -m "config in progress.. :rocket:"
2021/11/15 00:02:55 Failed to get config: reading file: open \c\personal\projects\uni-blog\ready.yaml: The system cannot find the path specified.
```

my ready.yaml  
```
tasks:
  - name: format
    command: gofumpt -extra -l -w .
```

any help please?  

Thanks in advance  
[am using this go template](https://github.com/raliqala/golang-fibre-boilerplate)

**Comment by lewislbr** [comment]
Thanks for reporting. Windows support is not fully implemented yet. I'll add it soon.

**Comment by lewislbr** [comment]
I prepared this branch: https://github.com/lewislbr/ready/tree/windows-support. Can you test it?

**Comment by raliqala** [comment]
I ran go install github.com/lewislbr/ready@windows-support  
it seems to work but now it show error related with PATH  
![image](https://user-images.githubusercontent.com/30502407/142946820-4fcbe6b3-5b24-424c-a679-7cf06b68b307.png)

**Comment by raliqala** [comment]
i went into pre-commit and removed the space/first empty line then it worked and produced that error, this might be me maybe i did not configure everything correctly, am kinder new in go

**Comment by lewislbr** [comment]
Yes that was it, thanks! I updated the branch, feel free to test it again

**Comment by raliqala** [comment]
now i get  this error when i re-install
 go install: github.com/lewislbr/ready@window-support: github.com/lewislbr/ready@window-support: invalid version: unknown revision window-support

**Comment by lewislbr** [comment]
Try `go install github.com/lewislbr/ready@bf55f6c9089704db6858bdf6293d408a033bc97f`

**Comment by raliqala** [comment]
it works thanks

**Comment by lewislbr** [comment]
Perfect, then I will add the change in https://github.com/lewislbr/ready/pull/5 so we can merge it. Thanks for your help!

**Comment by lewislbr** [comment]
Released: https://github.com/lewislbr/ready/releases/tag/v0.6.1. Now the changes will be available on `go install github.com/lewislbr/ready@latest`.
